<?php
/**
 * TPMeta_Builder_Codegen
 *
 * Generates a clean PHP file from a builder JSON schema. The output
 * uses the public TPMeta_Options API and is safe to commit to a theme.
 *
 * @package    tpmeta
 * @subpackage tpmeta/options/builder
 * @since      1.6.0
 */

if ( ! defined( 'ABSPATH' ) ) exit;

class TPMeta_Builder_Codegen {

	/**
	 * Build PHP source from a single panel schema.
	 *
	 * @param array $panel Builder panel schema.
	 * @return string Full PHP file contents (with <?php opener).
	 */
	public static function from_panel( array $panel ) {
		$opt_name   = isset( $panel['opt_name'] ) ? $panel['opt_name'] : 'tpmeta_panel';
		$generated  = gmdate( 'Y-m-d H:i:s' ) . ' UTC';
		$args_php   = self::array_to_php( self::panel_args_array( $panel ), 1 );
		$sections   = '';

		if ( ! empty( $panel['sections'] ) && is_array( $panel['sections'] ) ) {
			foreach ( $panel['sections'] as $section ) {
				$sections .= self::section_block( $opt_name, (array) $section );
			}
		}

		$opt_var = '$opt_name';

		return <<<PHP
<?php
/**
 * ThemePure Options Panel — generated by the TPMeta Options Builder.
 *
 * Generated:  {$generated}
 * Panel ID:   {$opt_name}
 *
 * Re-baking this file from the builder will overwrite manual edits.
 *
 * Read values:
 *   tpmeta_get_option( 'field_id', \$default );
 *   get_theme_mod( 'field_id', \$default );
 */

if ( ! defined( 'ABSPATH' ) ) exit;
if ( ! class_exists( 'TPMeta_Options' ) ) return;

add_action( 'init', function () {

	{$opt_var} = '{$opt_name}';

	TPMeta_Options::set_args( {$opt_var}, {$args_php} );

{$sections}
}, 8 );
PHP;
	}

	/**
	 * @param array $panel
	 * @return array
	 */
	protected static function panel_args_array( array $panel ) {
		$out = array(
			'menu_title'             => isset( $panel['menu_title'] )    ? $panel['menu_title']    : '',
			'page_title'             => isset( $panel['page_title'] )    ? $panel['page_title']    : '',
			'menu_slug'              => isset( $panel['menu_slug'] )     ? $panel['menu_slug']     : ( isset( $panel['opt_name'] ) ? $panel['opt_name'] : '' ),
			'menu_icon'              => isset( $panel['menu_icon'] )     ? $panel['menu_icon']     : 'dashicons-admin-generic',
			'menu_position'          => isset( $panel['menu_position'] ) ? (int) $panel['menu_position'] : 60,
			'capability'             => isset( $panel['capability'] )    ? $panel['capability']    : 'manage_options',
			'output_css'             => ! empty( $panel['output_css'] ),
			// When true, TPMeta_Customizer mirrors this panel into the WP
			// Customizer (Appearance → Customize) under the same opt_name.
			'customizer_integration' => ! empty( $panel['customizer_integration'] ),
		);

		// Customizer panel order. Only emit when set so panels saved before
		// this key existed bake with their previous output (TPMeta_Customizer
		// falls back to menu_position → 160).
		if ( isset( $panel['customizer_priority'] ) && '' !== (string) $panel['customizer_priority'] && is_numeric( $panel['customizer_priority'] ) ) {
			$out['customizer_priority'] = (int) $panel['customizer_priority'];
		}

		return $out;
	}

	/**
	 * @param string $opt_name
	 * @param array  $section
	 * @return string
	 */
	protected static function section_block( $opt_name, array $section ) {
		$arr = array(
			'id'          => isset( $section['id'] )          ? $section['id']          : '',
			'title'       => isset( $section['title'] )       ? $section['title']       : '',
			'icon'        => isset( $section['icon'] )        ? $section['icon']        : '',
			'description' => isset( $section['description'] ) ? $section['description'] : '',
			'fields'      => array(),
		);

		// v2 row-based format: sections store fields inside rows[*].fields
		if ( ! empty( $section['rows'] ) && is_array( $section['rows'] ) ) {
			foreach ( $section['rows'] as $row ) {
				if ( empty( $row['fields'] ) || ! is_array( $row['fields'] ) ) continue;
				foreach ( $row['fields'] as $field ) {
					$arr['fields'][] = self::field_array( (array) $field );
				}
			}
		}

		// v1 legacy flat-fields format (fallback for older schemas)
		if ( empty( $arr['fields'] ) && ! empty( $section['fields'] ) && is_array( $section['fields'] ) ) {
			foreach ( $section['fields'] as $field ) {
				$arr['fields'][] = self::field_array( (array) $field );
			}
		}

		$php = self::array_to_php( $arr, 1 );
		return "\tTPMeta_Options::set_section( \$opt_name, {$php} );\n\n";
	}

	/**
	 * Translate a builder field into the framework field shape.
	 *
	 * @param array $field
	 * @return array
	 */
	protected static function field_array( array $field ) {
		$out = array(
			'id'    => isset( $field['id'] )    ? $field['id']    : '',
			'type'  => isset( $field['type'] )  ? $field['type']  : 'text',
			'label' => isset( $field['label'] ) ? $field['label'] : '',
		);

		if ( ! empty( $field['description'] ) ) $out['description'] = $field['description'];
		if ( ! empty( $field['placeholder'] ) ) $out['placeholder'] = $field['placeholder'];
		if ( array_key_exists( 'default', $field ) && '' !== $field['default'] ) {
			$out['default'] = $field['default'];
		}

		// options: array<{value,label}> → assoc.
		if ( ! empty( $field['options'] ) && is_array( $field['options'] ) ) {
			$assoc = array();
			foreach ( $field['options'] as $opt ) {
				$opt = (array) $opt;
				if ( ! isset( $opt['value'] ) ) continue;
				$assoc[ $opt['value'] ] = isset( $opt['label'] ) ? $opt['label'] : $opt['value'];
			}
			if ( $assoc ) {
				// Use 'choices' for types that follow Kirki/WP-Customizer naming convention.
				$uses_choices = in_array( $out['type'], array( 'tabs', 'radio_buttonset' ), true );
				$out[ $uses_choices ? 'choices' : 'options' ] = $assoc;
			}
		}

		// output: array<{selector,property}> → assoc.
		if ( ! empty( $field['output'] ) && is_array( $field['output'] ) ) {
			$assoc = array();
			foreach ( $field['output'] as $rule ) {
				$rule = (array) $rule;
				if ( empty( $rule['selector'] ) || empty( $rule['property'] ) ) continue;
				$assoc[ $rule['selector'] ] = $rule['property'];
			}
			if ( $assoc ) {
				$out['output'] = $assoc;
			}
		}

		// conditional: {field,operator,value} → indexed array.
		if ( ! empty( $field['conditional'] ) && is_array( $field['conditional'] ) ) {
			$c = $field['conditional'];
			if ( ! empty( $c['field'] ) ) {
				$out['conditional'] = array(
					$c['field'],
					isset( $c['operator'] ) ? $c['operator'] : '==',
					isset( $c['value'] )    ? $c['value']    : '',
				);
			}
		}

		// Switch: preserve data_type in baked PHP.
		if ( 'switch' === $out['type'] && ! empty( $field['data_type'] ) ) {
			$out['data_type'] = $field['data_type'];
		}

		// Image: preserve return_format ('array' | 'id' | 'url') in baked PHP.
		if ( 'image' === $out['type'] && ! empty( $field['return_format'] ) ) {
			$out['return_format'] = $field['return_format'];
		}

		// Dimension: preserve range-slider config (units / min / max / step) so
		// the baked PHP renders the same slider bounds the builder showed.
		// Storage shape stays "150px" scalar — these only configure the UI.
		if ( 'dimension' === $out['type'] ) {
			if ( ! empty( $field['units'] ) && is_array( $field['units'] ) ) {
				$out['units'] = array_values( $field['units'] );
			}
			foreach ( array( 'min', 'max', 'step' ) as $_dim_k ) {
				if ( isset( $field[ $_dim_k ] ) && '' !== (string) $field[ $_dim_k ] && is_numeric( $field[ $_dim_k ] ) ) {
					$out[ $_dim_k ] = 0 + $field[ $_dim_k ];
				}
			}
		}

		// Post Select: preserve query config in baked PHP.
		if ( 'post_select' === $out['type'] ) {
			if ( ! empty( $field['post_type'] ) )       $out['post_type']       = $field['post_type'];
			if ( ! empty( $field['save_format'] ) )     $out['save_format']     = $field['save_format'];
			if ( ! empty( $field['initial_limit'] ) )   $out['initial_limit']   = (int) $field['initial_limit'];
			if ( ! empty( $field['taxonomy_filter'] ) ) $out['taxonomy_filter'] = (array) $field['taxonomy_filter'];
			if ( ! empty( $field['meta_filters'] ) )    $out['meta_filters']    = (array) $field['meta_filters'];
			if ( ! empty( $field['placeholder'] ) )     $out['placeholder']     = $field['placeholder'];
		}

		// Repeater: column layout.
		if ( 'repeater' === $out['type'] && ! empty( $field['columns'] ) ) {
			$out['columns'] = max( 1, min( 4, (int) $field['columns'] ) );
		}

		// Repeater: bake sub-fields as a SEQUENTIAL array of {id, type, …}.
		// Templates iterate `foreach ( $field['fields'] as $sf )` and read
		// $sf['id'] / $sf['type'] directly, so id MUST live inside each entry.
		if ( 'repeater' === $out['type'] && ! empty( $field['fields'] ) && is_array( $field['fields'] ) ) {
			$sf_out = array();
			foreach ( $field['fields'] as $sf ) {
				$sf      = (array) $sf;
				$sf_id   = isset( $sf['id'] ) ? $sf['id'] : '';
				$sf_type = isset( $sf['type'] ) ? $sf['type'] : 'text';
				if ( ! $sf_id ) continue;

				$sf_arr = array(
					'id'      => $sf_id,
					'type'    => $sf_type,
					'label'   => isset( $sf['label'] )   ? $sf['label']   : '',
					// Explicit empty default so the generated code is self-documenting.
					'default' => isset( $sf['default'] ) ? $sf['default'] : '',
				);
				if ( ! empty( $sf['description'] ) ) $sf_arr['description'] = $sf['description'];
				if ( ! empty( $sf['placeholder'] ) ) $sf_arr['placeholder'] = $sf['placeholder'];

				if ( ! empty( $sf['options'] ) && is_array( $sf['options'] ) ) {
					$assoc = array();
					foreach ( $sf['options'] as $opt ) {
						$opt = (array) $opt;
						if ( empty( $opt['value'] ) ) continue;
						$assoc[ $opt['value'] ] = isset( $opt['label'] ) ? $opt['label'] : $opt['value'];
					}
					if ( $assoc ) {
						// Match top-level: tabs + radio_buttonset use 'choices'.
						$out_key = in_array( $sf_type, array( 'tabs', 'radio_buttonset' ), true ) ? 'choices' : 'options';
						$sf_arr[ $out_key ] = $assoc;
					}
				}

				// Switch sub-field: preserve data_type in the baked file so
				// the read-side cast (theme_mod / tpmeta_field) keeps working
				// after the panel is exported to PHP and the JSON store is
				// no longer the source of truth.
				if ( 'switch' === $sf_type && ! empty( $sf['data_type'] ) ) {
					$sf_arr['data_type'] = $sf['data_type'];
				}

				// Dimension sub-field: mirror the top-level dimension branch
				// (units / min / max / step) so a baked repeater renders its
				// slider bounds identically to the in-builder preview.
				if ( 'dimension' === $sf_type ) {
					if ( ! empty( $sf['units'] ) && is_array( $sf['units'] ) ) {
						$sf_arr['units'] = array_values( $sf['units'] );
					}
					foreach ( array( 'min', 'max', 'step' ) as $_sf_dim_k ) {
						if ( isset( $sf[ $_sf_dim_k ] ) && '' !== (string) $sf[ $_sf_dim_k ] && is_numeric( $sf[ $_sf_dim_k ] ) ) {
							$sf_arr[ $_sf_dim_k ] = 0 + $sf[ $_sf_dim_k ];
						}
					}
				}

				$sf_out[] = $sf_arr;
			}
			if ( $sf_out ) {
				$out['fields'] = $sf_out;
			}
		}

		return $out;
	}

	/**
	 * Pretty-print a PHP array to source. Tabs for indent, single-quoted
	 * strings, no var_export quirks.
	 *
	 * @param mixed $value
	 * @param int   $indent Level (1 = one tab).
	 * @return string
	 */
	public static function array_to_php( $value, $indent = 0 ) {
		$pad      = str_repeat( "\t", $indent );
		$pad_in   = str_repeat( "\t", $indent + 1 );

		if ( is_array( $value ) ) {
			if ( empty( $value ) ) {
				return 'array()';
			}
			$is_assoc = array_keys( $value ) !== range( 0, count( $value ) - 1 );
			$lines    = array();
			foreach ( $value as $k => $v ) {
				$rendered = self::array_to_php( $v, $indent + 1 );
				if ( $is_assoc ) {
					$lines[] = $pad_in . self::quote( (string) $k ) . ' => ' . $rendered . ',';
				} else {
					$lines[] = $pad_in . $rendered . ',';
				}
			}
			return "array(\n" . implode( "\n", $lines ) . "\n" . $pad . ')';
		}

		if ( is_bool( $value ) )   return $value ? 'true' : 'false';
		if ( is_null( $value ) )   return 'null';
		if ( is_int( $value ) )    return (string) $value;
		if ( is_float( $value ) )  return (string) $value;

		return self::quote( (string) $value );
	}

	/**
	 * Single-quote a PHP string literal safely.
	 *
	 * @param string $s
	 * @return string
	 */
	protected static function quote( $s ) {
		return "'" . str_replace( array( '\\', "'" ), array( '\\\\', "\\'" ), $s ) . "'";
	}
}
