<?php
/**
 * TPMeta_Metafields_Codegen
 *
 * Generates a standalone PHP file from one or more builder metabox JSON
 * schemas. The output uses the public `tp_meta_boxes` filter and is safe to
 * commit to a theme. Output shape mirrors the hand-written theme example
 * (positional `conditional`, assoc `options`, single-string `post_type` when
 * only one is selected, `choices` key for tabs/radio_buttonset).
 *
 * Reuses TPMeta_Builder_Codegen::array_to_php() for pretty-printing.
 *
 * @package    tpmeta
 * @subpackage tpmeta/metafields-builder
 * @since      1.7.1
 */

if ( ! defined( 'ABSPATH' ) ) exit;

class TPMeta_Metafields_Codegen {

	/**
	 * Build PHP source from one or more builder metabox schemas.
	 *
	 * Emits a single `add_filter('tp_meta_boxes', ...)` callback that appends
	 * each metabox via `$meta_boxes[] = array(...);` — matching the structure
	 * of the hand-written theme example.
	 *
	 * @param array  $boxes         Array of metabox arrays (builder JSON shape).
	 * @param string $callback_name PHP function name used as the filter callback.
	 * @return string Full PHP file contents (with `<?php` opener).
	 */
	public static function from_metaboxes( array $boxes, $callback_name = 'tpmeta_baked_metaboxes' ) {
		$generated     = gmdate( 'Y-m-d H:i:s' ) . ' UTC';
		$count         = count( $boxes );
		$callback_name = self::sanitize_callback_name( $callback_name );

		$body = '';
		foreach ( $boxes as $box ) {
			$arr  = self::metabox_to_filter_array( (array) $box );
			$php  = TPMeta_Builder_Codegen::array_to_php( $arr, 2 );
			$body .= "\t\t\$meta_boxes[] = {$php};\n\n";
		}

		// HEREDOC: escape `$` inside PHP we want literal in the output.
		return <<<PHP
<?php
/**
 * ThemePure Metaboxes — generated by the PureFields Metabox Builder.
 *
 * Generated:  {$generated}
 * Metaboxes:  {$count}
 *
 * Re-baking from the builder will overwrite this file.
 *
 * Read values:
 *   tpmeta_field( 'field_id', \$post_id );
 *   get_post_meta( \$post_id, 'field_id', true );
 */

if ( ! defined( 'ABSPATH' ) ) exit;

if ( ! function_exists( '{$callback_name}' ) ) {
	function {$callback_name}( \$meta_boxes ) {

{$body}		return \$meta_boxes;
	}
	add_filter( 'tp_meta_boxes', '{$callback_name}' );
}
PHP;
	}

	/**
	 * Build PHP source for one or more user-target builder records.
	 *
	 * Emits a single `add_filter('tp_user_meta', ...)` callback that appends
	 * each record as a `{label, fields, capability?}` block. The generated
	 * callback also normalises the legacy single-block filter shape
	 * (`{label, fields}` returned directly) to an array, matching the
	 * runtime behaviour of `tpmeta_get_user_meta_blocks()` in class-metabox.php.
	 *
	 * @param array  $boxes         Array of builder records with target='user'.
	 * @param string $callback_name PHP function name used as the filter callback.
	 * @return string Full PHP file contents (with `<?php` opener).
	 */
	public static function from_user_meta( array $boxes, $callback_name = 'tpmeta_baked_user_meta' ) {
		$generated     = gmdate( 'Y-m-d H:i:s' ) . ' UTC';
		$count         = count( $boxes );
		$callback_name = self::sanitize_callback_name( $callback_name );

		$body = '';
		foreach ( $boxes as $box ) {
			$arr  = self::user_meta_to_filter_array( (array) $box );
			$php  = TPMeta_Builder_Codegen::array_to_php( $arr, 2 );
			$body .= "\t\t\$blocks[] = {$php};\n\n";
		}

		return <<<PHP
<?php
/**
 * ThemePure User Meta — generated by the PureFields Metabox Builder.
 *
 * Generated:  {$generated}
 * Blocks:     {$count}
 *
 * Re-baking from the builder will overwrite this file.
 *
 * Read values:
 *   get_user_meta( \$user_id, 'field_id', true );
 */

if ( ! defined( 'ABSPATH' ) ) exit;

if ( ! function_exists( '{$callback_name}' ) ) {
	function {$callback_name}( \$blocks ) {
		if ( empty( \$blocks ) || ! is_array( \$blocks ) ) {
			\$blocks = array();
		} elseif ( isset( \$blocks['fields'] ) ) {
			// Legacy single-block shape — normalise to array.
			\$blocks = array( \$blocks );
		}

{$body}		return \$blocks;
	}
	add_filter( 'tp_user_meta', '{$callback_name}' );
}
PHP;
	}

	/**
	 * Build PHP source for a mixed selection (post-target + user-target records).
	 * Emits a single file with one `<?php` opener and two `add_filter()` callbacks
	 * — one for `tp_meta_boxes`, one for `tp_user_meta` — so the bake produces a
	 * single committable file instead of two.
	 *
	 * @param array  $post_boxes  Post-target records (target='post' or absent).
	 * @param array  $user_boxes  User-target records (target='user').
	 * @param string $cb_post     Callback function name for the post filter.
	 * @param string $cb_user     Callback function name for the user filter.
	 * @return string Full PHP file contents.
	 */
	public static function compose_combined( array $post_boxes, array $user_boxes, $cb_post = 'tpmeta_baked_metaboxes', $cb_user = 'tpmeta_baked_user_meta' ) {
		$generated  = gmdate( 'Y-m-d H:i:s' ) . ' UTC';
		$post_count = count( $post_boxes );
		$user_count = count( $user_boxes );
		$cb_post    = self::sanitize_callback_name( $cb_post );
		$cb_user    = self::sanitize_callback_name( $cb_user );

		$post_body = '';
		foreach ( $post_boxes as $box ) {
			$arr  = self::metabox_to_filter_array( (array) $box );
			$php  = TPMeta_Builder_Codegen::array_to_php( $arr, 2 );
			$post_body .= "\t\t\$meta_boxes[] = {$php};\n\n";
		}

		$user_body = '';
		foreach ( $user_boxes as $box ) {
			$arr  = self::user_meta_to_filter_array( (array) $box );
			$php  = TPMeta_Builder_Codegen::array_to_php( $arr, 2 );
			$user_body .= "\t\t\$blocks[] = {$php};\n\n";
		}

		return <<<PHP
<?php
/**
 * ThemePure Metafields — generated by the PureFields Metabox Builder.
 *
 * Generated:    {$generated}
 * Post boxes:   {$post_count}
 * User blocks:  {$user_count}
 *
 * Re-baking from the builder will overwrite this file.
 */

if ( ! defined( 'ABSPATH' ) ) exit;

if ( ! function_exists( '{$cb_post}' ) ) {
	function {$cb_post}( \$meta_boxes ) {

{$post_body}		return \$meta_boxes;
	}
	add_filter( 'tp_meta_boxes', '{$cb_post}' );
}

if ( ! function_exists( '{$cb_user}' ) ) {
	function {$cb_user}( \$blocks ) {
		if ( empty( \$blocks ) || ! is_array( \$blocks ) ) {
			\$blocks = array();
		} elseif ( isset( \$blocks['fields'] ) ) {
			\$blocks = array( \$blocks );
		}

{$user_body}		return \$blocks;
	}
	add_filter( 'tp_user_meta', '{$cb_user}' );
}
PHP;
	}

	/**
	 * Convert a single user-target builder record (sections → rows → fields)
	 * into the `tp_user_meta` filter-format block `{label, fields, capability?}`.
	 * Reuses `field_to_filter_array()` so option assoc-ing, conditional
	 * normalisation, and repeater sub-field handling stay in one place.
	 *
	 * @param array $box
	 * @return array
	 */
	public static function user_meta_to_filter_array( array $box ) {
		$fields = array();
		if ( ! empty( $box['sections'] ) && is_array( $box['sections'] ) ) {
			foreach ( $box['sections'] as $section ) {
				$rows = isset( $section['rows'] ) && is_array( $section['rows'] ) ? $section['rows'] : array();
				foreach ( $rows as $row ) {
					$row_fields = isset( $row['fields'] ) && is_array( $row['fields'] ) ? $row['fields'] : array();
					foreach ( $row_fields as $f ) {
						$fields[] = self::field_to_filter_array( (array) $f );
					}
				}
			}
		} elseif ( ! empty( $box['fields'] ) && is_array( $box['fields'] ) ) {
			// Legacy flat builder format.
			foreach ( $box['fields'] as $f ) {
				$fields[] = self::field_to_filter_array( (array) $f );
			}
		}

		$out = array(
			'label'  => isset( $box['title'] ) ? $box['title'] : '',
			'fields' => $fields,
		);
		if ( ! empty( $box['capability'] ) ) {
			$out['capability'] = $box['capability'];
		}
		return $out;
	}

	/**
	 * Convert a single builder metabox (sections → rows → fields) into the
	 * flat filter-format array (`fields[]`).
	 *
	 * @param array $box
	 * @return array
	 */
	public static function metabox_to_filter_array( array $box ) {
		// post_type: builder stores array; emit string when single (matches theme example).
		$post_types = isset( $box['post_type'] ) ? (array) $box['post_type'] : array();
		$post_type  = ( count( $post_types ) === 1 ) ? $post_types[0] : $post_types;
		if ( empty( $post_type ) ) {
			$post_type = 'post';
		}

		$fields = array();
		if ( ! empty( $box['sections'] ) && is_array( $box['sections'] ) ) {
			foreach ( $box['sections'] as $section ) {
				$rows = isset( $section['rows'] ) && is_array( $section['rows'] ) ? $section['rows'] : array();
				foreach ( $rows as $row ) {
					$row_fields = isset( $row['fields'] ) && is_array( $row['fields'] ) ? $row['fields'] : array();
					foreach ( $row_fields as $f ) {
						$fields[] = self::field_to_filter_array( (array) $f );
					}
				}
			}
		} elseif ( ! empty( $box['fields'] ) && is_array( $box['fields'] ) ) {
			// Legacy flat builder format.
			foreach ( $box['fields'] as $f ) {
				$fields[] = self::field_to_filter_array( (array) $f );
			}
		}

		$out = array(
			'metabox_id' => isset( $box['metabox_id'] ) ? $box['metabox_id'] : '',
			'title'      => isset( $box['title'] )      ? $box['title']      : '',
			'post_type'  => $post_type,
			'context'    => isset( $box['context'] )    ? $box['context']    : 'normal',
			'priority'   => isset( $box['priority'] )   ? $box['priority']   : 'default',
			'columns'    => max( 1, absint( isset( $box['columns'] ) ? $box['columns'] : 1 ) ),
			'fields'     => $fields,
		);

		// Pass-through for optional top-level keys (post_format, etc.).
		$skip = array( 'metabox_id', 'title', 'post_type', 'context', 'priority', 'columns', 'fields', 'sections' );
		foreach ( $box as $k => $v ) {
			if ( in_array( $k, $skip, true ) ) continue;
			// Skip builder-internal markers (prefixed with underscore).
			if ( is_string( $k ) && '_' === substr( $k, 0, 1 ) ) continue;
			$out[ $k ] = $v;
		}

		return $out;
	}

	/**
	 * Convert a single builder field into the filter-format field shape.
	 *
	 * @param array $f
	 * @return array
	 */
	public static function field_to_filter_array( array $f ) {
		$type = isset( $f['type'] ) ? $f['type'] : 'text';

		$out = array(
			'label' => isset( $f['label'] ) ? $f['label'] : '',
			'id'    => isset( $f['id'] )    ? $f['id']    : '',
			'type'  => $type,
		);

		if ( array_key_exists( 'default', $f ) ) {
			$out['default'] = self::normalize_default( $type, $f['default'] );
		}
		if ( ! empty( $f['placeholder'] ) ) $out['placeholder'] = $f['placeholder'];
		if ( ! empty( $f['description'] ) ) $out['description'] = $f['description'];

		// options → assoc; tabs/radio_buttonset use `choices` key.
		if ( ! empty( $f['options'] ) && is_array( $f['options'] ) ) {
			$assoc = self::options_to_assoc( $f['options'] );
			if ( $assoc ) {
				$key = in_array( $type, array( 'tabs', 'radio_buttonset' ), true ) ? 'choices' : 'options';
				$out[ $key ] = $assoc;
			}
		}
		// Builder may also store `choices` directly (multicolor seeds, etc.).
		if ( ! empty( $f['choices'] ) && empty( $out['choices'] ) && empty( $out['options'] ) && is_array( $f['choices'] ) ) {
			$assoc = self::options_to_assoc( $f['choices'] );
			if ( $assoc ) {
				$key = in_array( $type, array( 'tabs', 'radio_buttonset' ), true ) ? 'choices' : 'options';
				$out[ $key ] = $assoc;
			}
		}

		// conditional → positional [id, op, val]. Always emit (matches theme example,
		// which writes `'conditional' => array()` even when empty).
		$out['conditional'] = self::cond_to_positional( isset( $f['conditional'] ) ? $f['conditional'] : array() );

		// Repeater: recursively bake sub-fields.
		if ( 'repeater' === $type && ! empty( $f['fields'] ) && is_array( $f['fields'] ) ) {
			$sub = array();
			foreach ( $f['fields'] as $sf ) {
				$sub[] = self::field_to_filter_array( (array) $sf );
			}
			$out['fields'] = $sub;
		}

		// Pass-through any keys we didn't explicitly emit (multiple, bind, parent,
		// post_type for select_posts, data_type, save_format, etc.).
		$skip = array( 'id', 'type', 'label', 'default', 'placeholder', 'description', 'options', 'choices', 'conditional', 'fields' );
		foreach ( $f as $k => $v ) {
			if ( in_array( $k, $skip, true ) ) continue;
			if ( is_string( $k ) && '_' === substr( $k, 0, 1 ) ) continue; // builder-internal
			$out[ $k ] = $v;
		}

		return $out;
	}

	/**
	 * Multicolor stores its default as a JSON string in the builder; emit a
	 * proper PHP array so the generated file is clean and consumers can read
	 * it without an extra json_decode step.
	 */
	private static function normalize_default( $type, $default ) {
		if ( 'multicolor' === $type && is_string( $default ) && '' !== $default ) {
			$decoded = json_decode( $default, true );
			if ( is_array( $decoded ) ) return $decoded;
		}
		return $default;
	}

	/**
	 * Convert builder options ([{value,label}, …]) to assoc {value: label}.
	 * Already-assoc input is returned unchanged. Falls back to a derived key
	 * when value is missing (matches the loader's behaviour).
	 */
	private static function options_to_assoc( array $opts ) {
		if ( empty( $opts ) ) return array();
		if ( array_keys( $opts ) !== range( 0, count( $opts ) - 1 ) ) {
			return $opts;
		}
		$assoc = array();
		$idx   = 0;
		foreach ( $opts as $opt ) {
			$opt   = (array) $opt;
			$label = isset( $opt['label'] ) ? $opt['label'] : '';
			if ( ! isset( $opt['value'] ) || '' === $opt['value'] ) {
				$value = sanitize_key( $label );
				if ( '' === $value ) $value = 'option_' . $idx;
			} else {
				$value = $opt['value'];
			}
			$assoc[ $value ] = '' !== $label ? $label : $value;
			$idx++;
		}
		return $assoc;
	}

	/**
	 * Normalise conditional to positional [id, op, value]. Accepts either the
	 * builder's assoc {field, operator, value} or the already-positional shape.
	 */
	private static function cond_to_positional( $cond ) {
		if ( empty( $cond ) || ! is_array( $cond ) ) return array();
		if ( isset( $cond['field'] ) && '' !== $cond['field'] ) {
			return array(
				$cond['field'],
				isset( $cond['operator'] ) ? $cond['operator'] : '==',
				isset( $cond['value'] )    ? $cond['value']    : '',
			);
		}
		if ( isset( $cond[0] ) && '' !== $cond[0] ) {
			return array(
				$cond[0],
				isset( $cond[1] ) ? $cond[1] : '==',
				isset( $cond[2] ) ? $cond[2] : '',
			);
		}
		return array();
	}

	/**
	 * Reduce arbitrary input to a valid PHP function name.
	 */
	private static function sanitize_callback_name( $name ) {
		$name = strtolower( (string) $name );
		$name = preg_replace( '/[^a-z0-9_]+/', '_', $name );
		$name = preg_replace( '/^[^a-z_]+/', '', $name );
		$name = trim( $name, '_' );
		return $name !== '' ? $name : 'tpmeta_baked_metaboxes';
	}
}
